server:
  port: 9500
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.62.244:3306/ms-order?useSSL=false&characterEncoding=utf-8
      username: root
      password: YYJNo$QsaaSjgb8U3JoigB
      driver-class-name: com.mysql.jdbc.Driver
      minIdle: 1
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 25200000
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    database: 0
    host: 39.104.28.40
    port: 6379
    password: YYJNo$QsaaSjgb8U3JoigB
  application:
    name: ${appName}
logging:
  config: classpath:logback-spring.xml
  <#noparse>path: /opt/logs/scdemo/serverb/${spring.application.name}</#noparse>
mybatis:
  config-location:  classpath:/mybatis-config.xml
  mapper-locations: classpath:/mybatis/*.xml

swagger:
#  开启当前服务的 swagger
  enabled: true
#  设置当前服务扫描的包路径
  base:
    package: ${basepackage}.web.controller.admin,${basepackage}.web.controller.mobile,${basepackage}.web.controller.web

#  不显示nepxion discovery的swagger信息，如果要显示的话，需要将base.package配置到 service下一级
  service:
    enabled: false


